### ISSUE TITLE
DFP API Deprecation

### ISSUE THREAD

**Issue by Andrewm4894pmc** [StevenMMortimer/rdfp#1]
Hi, 

I got the below notice about DFP deprecating an API which i think relates to the app i created for this package to use. 

Just wanted to make you aware of this in case not on your radar. 

I'm just assuming at some stage users of your package would just need to update once you switch to the new api maybe. Or maybe its more complicated then that?

Seems like a while yet before they turn it off. 

Here is the blog post http://googleadsdeveloper.blogspot.ie/2016/10/sunset-of-dfp-api-v201508-and-v201511.html 

Would be happy to help test or anything if i can be of any use. Love the package makes dealing with DFP so much easier. 

Cheers,
Andy

![image](https://cloud.githubusercontent.com/assets/14315274/19470580/f3f25eda-9517-11e6-9f4e-7674282473e3.png)

**Comment by StevenMMortimer** [comment]
Thanks @Andrewm4894pmc. About a month ago I updated the package API version to 201608 starting with b8db68e. You should be good to go if you reinstall the package.
